### ISSUE TITLE
Can you update it to 5.6?  thank you!

### ISSUE THREAD

**Issue by mingliang2645751** [Ginurx/MecanimEventSystem#2]
Can you update it to 5.6?

**Comment by Ginurx** [comment]
I don't know how people are still using it nowadays.  
This plugin was written long ago and used many internal editor classes and methods.
Unity has changed a lot of APIs in 5.x life cycle. It's hard to track those changes from version to version.
I would evaluate the possibility of porting it to Unity 2017.

**Comment by Ginurx** [comment]
I thought it still works in Unity 2017.

**Comment by Ginurx** [comment]
Updated to 2017.2
