### ISSUE TITLE
大神您好，能加qq交流下吗？

### ISSUE THREAD

**Issue by FlameskyDexive** [Ginurx/MecanimEventSystem#3]
最近发现了这个技能编辑器，超级棒，有些地方想不太明白，比如动画事件的解析，为何不在初始化的时候根据动画直接AddEvent，而是通过在Update里头通过SendMessage的方式去执行事件呢？这样做是否是有啥优势？可否加个qq，有好多问题想请教大佬呢

**Comment by Ginurx** [comment]
动画的event本质上也是Update  + SendMessage
SendMessage性能上有损失但更灵活，有多个接收者的情况不需要增加额外的配置，增加脚本声明函数就能处理动画事件了
动画的event有一个很大的缺陷，动作无法复用。这个工具是针对状态，而不是动画添加事件，动画文件可以在多个状态上自由复用。
另外，有些处理方法是有历史原因的，之所以会有这个工具，因为Mecanim在4.x刚推出的时候，Mecanim并不支持animation event，当时做事件只能在代码里switch当前状态

**Comment by FlameskyDexive** [comment]
soga，了解了，按照这样的做法，把编辑器数据导出一份配表，然后在服务端也做类似的解析，服务端处理动画事件应该跟客户端也就差不多了，我是想把数据导出csv配表，以供后续服务端计算战斗的时候也需要跟客户端一样的动画事件数据，这种做法应该是可行的把？

**Comment by Ginurx** [comment]
恐怕还有很多东西要处理吧，光看动画事件应该问题不大，但是它本质上还是根据状态机来处理的，除非服务器也有一样的状态机，或是状态本身不复杂，就是纯放动画的

**Comment by FlameskyDexive** [comment]
嗯嗯，，服务端去构建一套状态机就完事了应该，，谢过大神了哈
