### ISSUE TITLE
No License 

### ISSUE THREAD

**Issue by tonypatino** [Ginurx/MecanimEventSystem#4]
I see that your code doesn’t have a license, but I also saw on the Unity forum that you intend for people to use this freely.  

https://forum.unity.com/threads/event-system-for-mecanim.163731/

Could you please add a free software license to your codebase, in a text file? Otherwise it may be legally problematic to use this tool.

Perhaps you can add the MIT license?
https://opensource.org/licenses/MIT

**Comment by Ginurx** [comment]
Added an MIT License :)
